Implementación Mutex Global, por Fia y por Asiento
Molter73/movies pull request #2
Opened 2024-04-15 15:36 UTC by bmsjale93

2024-04-15 16:11 UTC, Molter73 requested changes
Dejo un par de comentarios, de momento mis 3 principales preocupaciones son:
- El código no compila.
- Los asientos se deben elegir de forma aleatoria.
- Habíamos quedado en utilizar `pthread_mutex_t`, pero la implementación usa semáforos.

2024-04-15 16:11 UTC, Molter73 commented on .vscode/settings.json
Quitemos este archivo del repo, es configuración local que no tiene por qué estar aquí. Agrega la siguiente línea al archivo `.gitignore`
```
.vscode/
```

2024-04-15 16:11 UTC, Molter73 commented on src/client.h
>  client_t* client_new(movie_t* movie, int id);
Tienes que cambiar `client_new` aquí también, tiene una firma distinta en client.c y por eso no te compila el código.

2024-04-15 16:11 UTC, Molter73 commented on src/client.h
> +pthread_mutex_t* seat_mutexes;
No hace falta exponer los mutex, se deberían utilizar solamente en `client.c` y ningún otro módulo debería necesitar accederlos.
```suggestion
```

2024-04-15 16:11 UTC, Molter73 commented on src/movie.h
> +    sem_t* seat_locks; // Array de Semáforos, uno por asiento.
Estos tres debería estar definidos en `src/client.c` por una cuestión lógica. Si los definimos en `movie.h`, entonces el bloqueo de `movie_t` debería hacerse en `movie.c` y entonces deberíamos mover bastante más lógica a esta parte.
```suggestion
```

2024-04-15 16:11 UTC, Molter73 commented on src/movie.h
> +#include <semaphore.h>
Como sólo vamos a utilizar pthreads, tiene más sentido utilizar `pthread_mutex`, no semáforos.
```suggestion
```

2024-04-15 16:11 UTC, Molter73 commented on src/client.c
> +        for (unsigned int j = 0; j < movie->ncols; j++) {
Queremos que los hilos intenten reservar un asiento aleatorio, no reservarlos secuencialmente. Utiliza `rand` o `rand_r` para obtener dos números que estén en el rango de nrows y ncols e intenta reservarlo directamente
https://linux.die.net/man/3/rand

2024-04-15 16:11 UTC, Molter73 commented on src/client.c
> +        for (unsigned int j = 0; j < movie->ncols; j++) {
Nota a parte, no necesitas tomar el mutex antes de obtener el valor aleatorio.

2024-04-15 16:11 UTC, Molter73 commented on src/client.c
> +        for (unsigned int j = 0; j < movie->ncols; j++) {
Y el comentario aplica para los 3 métodos, es un requisito de la actividad.

2024-04-15 16:11 UTC, Molter73 commented on src/movie.c
> +    }
No hace falta iniciar todos los mutex de todas las variantes, sólo vamos a utilizar una basada en el método de reserva seleccionada por el usuario. Mueve esta lógica al archivo `client.c` en una función `int client_init(int method)` y podemos hacer la limpieza de esto en un `void client_destroy()`

2024-04-15 16:11 UTC, Molter73 commented on src/client.h
>  client_t* client_new(movie_t* movie, int id);
Nota a parte, al menos intenta compilar el código antes de hacer commit y push 🤣

2024-04-16 09:44 UTC, Molter73 reviewed
Va tomando forma! 🎉 

Hazme un favor y además de los comentario que te dejé, cambia esta línea para que ejecute con más hebras, así nos asguramos que haya accesos múltiples a las mismas zonas de memoria: https://github.com/Molter73/movies/blob/842bff9627a050dbb174ef9f5766170cd8cd8879/.github/workflows/main.yml#L53

Algo así debería ir bien:
```yml
        run: ./movies -t 1000
```

2024-04-16 09:44 UTC, Molter73 commented on src/client.c
> +    int rand_col = rand() % movie->ncols;
Estas dos líneas no necesitan estar en la sección crítica, muévelas antes de `pthread_mutex_lock`. Si ThreadSanitizer te da problemas, intenta utilizar `rand_r` con una variable estática, algo así

```c
static int seed = 0xdeadbeef;
int row = rand_r(&seed) & movie->nrows;
int col = rand_r(&seed) & movie->ncols;
```

2024-04-16 09:44 UTC, Molter73 commented on src/client.c
> +    reserved     = movie_reserve_seat(movie, rand_col, rand_row, id);
Aquí puedes asignar directamente a `client->res.success`, no hace falta una variable intermedia. Tampoco veo necesario hacer una copia del id del cliente.
```suggestion
    client->res.success = movie_reserve_seat(movie, rand_col, rand_row, client->data.id);
```

2024-04-16 09:44 UTC, Molter73 commented on src/client.c
> +    int rand_col = rand() % movie->ncols;
Tampoco creo que haga falta aclarar que la fila y la columna son aleatorias.
```suggestion
    int row = rand() % movie->nrows;
    int col = rand() % movie->ncols;
```

2024-04-16 09:44 UTC, Molter73 commented on src/client.c
> +    int row          = id % movie->nrows;
Aquí la fila también debe ser aleatoria.

2024-04-16 09:44 UTC, Molter73 commented on src/client.c
> +    int rand_col = rand() % movie->ncols;
Mismo comentario sobre la asignación de columna y la sección crítica.

2024-04-16 09:44 UTC, Molter73 commented on src/client.c
> +    reserved     = movie_reserve_seat(movie, rand_col, row, id);
Mismo comentario de asignar a `client->data.reserved` y usar `client->data.id` directamente.

2024-04-16 09:44 UTC, Molter73 commented on src/client.c
> +    int rand_row   = rand_index / movie->ncols;
```suggestion
    int rand_row   = rand_index / movie->nrows;
```

2024-04-16 09:44 UTC, Molter73 commented on src/client.c
> +void* client_per_seat_mutex(void* arg) {
Los comentarios anteriores del nombre de `row` y `col`, asignar reserved y usar el id aplican a esta función también.

2024-04-16 09:44 UTC, Molter73 commented on src/client.c
> +    return pthread_create(&client->thread, NULL, client_run, client);
Propongo un par de alternativas aquí.
Primero, vuelve a poner el casteo aquí y vuelve a pasar sólo `&client->data` como parámetro.
```suggestion
    return pthread_create(&client->thread, NULL, (void* (*)(void*))client_run, &client->data);
```
Luego cambia la definición de `client_run` en la línea 24 para que sea así:
```c
client_res_t* (*client_run)(client_data_t*) = NULL;
```

Con este cambio, las otras 3 funciones de client_run van a tener que cambiar para ser iguales a esta, pero no será necesario hacer el casteo de `void*` a `client_data_t*`, dejando el código más limpio.

Finalmente, en las implementaciones de `client_run` podemos reservar y retornar un `client_res_t`, el cual luego se puede acceder y liberar en el llamado a `pthread_join` sobre el final de la ejecución del proceso. Para esto deberíamos cambiar `client_res_init` a `client_res_new`, quitar el miembro `res` de `client_t` y agregar una `client_res_free` para simplificar la liberación si complicamos el tipo.
```c
client_res_t* client_res_new() {
    client_res_t* res = (client_res_t*)malloc(sizeof(client_res_t));
    if (res == NULL) {
        return NULL;
    }

    res->success = false;
    return res;
}

void client_res_free(client_res_t* res) {
     free(res);
}
```

2024-04-16 09:44 UTC, Molter73 commented on src/client.c
> +    }
Por favor, crea un enum para que sea más fácil entender este switch case.
```c
typedef enum {
    GLOBAL = 0,
    ROW = 1,
    SEAT = 2,
} locking_method;
```

```suggestion
    switch (method) {
    case GLOBAL:
        client_run = client_global_mutex;
        break;
    case ROW:
        client_run = client_per_row_mutex;
        break;
    case SEAT:
        client_run = client_per_seat_mutex;
        break;
    default:
        client_run = NULL;
        free(client);
        return NULL;
    }
```

2024-04-16 09:44 UTC, Molter73 commented on src/client.c
> +    }
No hace falta el chequeo a null aquí, `free` ya hace esa comprobación internamente.
```
If ptr is NULL, no operation is performed. 
```
https://linux.die.net/man/3/free
```suggestion
     free(client);
```

2024-04-16 09:44 UTC, Molter73 commented on src/client.c
> +    case 2:
El enum propuesto en un comentario anterior también iría bien aquí
```suggestion
void client_init_mutexes(locking_method method, int nrows, int ncols) {
    switch (method) {
    case GLOBAL:
        pthread_mutex_init(&global_mutex, NULL);
        break;
    case ROW:
        row_mutexes = malloc(nrows * sizeof(pthread_mutex_t));
        for (int i = 0; i < nrows; i++) {
            pthread_mutex_init(&row_mutexes[i], NULL);
        }
        break;
    case SEAT:
```

2024-04-16 09:44 UTC, Molter73 commented on src/client.c
> +        pthread_mutex_init(&global_mutex, NULL);
El mutex global ya se inicializa con `PTHREAD_MUTEX_INITIALIZER`, en este caso no hace falta hacer nada, sólo el `break`
```suggestion
```

2024-04-16 09:44 UTC, Molter73 commented on src/client.c
> +        for (int i = 0; i < nrows * ncols; i++) {
Esto ya es ser tiquimiquis, pero podríamos usar una variable auxiliar aquí:
```suggestion
        int nseats = nrows * ncols;
        seat_mutexes = malloc(nseats * sizeof(pthread_mutex_t));
        for (int i = 0; i < nseats; i++) {
```

2024-04-16 09:44 UTC, Molter73 commented on src/client.c
> +        row_mutexes = malloc(nrows * sizeof(pthread_mutex_t));
Siempre que hagas un `malloc` o `calloc`  comprueba que haya sido exitoso por favor, en general nunca falla, pero nunca está demás ser cuidadoso. En este caso también deberíamos agregar un valor de retorno para indicar si el código debe continuar ejecutando o detenerse.
```suggestion
        row_mutexes = malloc(nrows * sizeof(pthread_mutex_t));
        if (row_mutexes == NULL) {
            return false;
        }
```

2024-04-16 09:44 UTC, Molter73 commented on src/client.c
> +        pthread_mutex_destroy(&global_mutex);
Entiendo que en el caso de inicializar el mutex con `PTHREAD_MUTEX_INIT` no sería necesario destruirlo.
```suggestion
```

2024-04-16 09:44 UTC, Molter73 commented on src/main.c
> +            }
`atoi` no es adecuado para comprobación de errores, por ejemplo, pasar un string que no sea un entero hace que `atoi` devuelva 0, cómo sabemos entonces si el usuario eligió 0 o ingresó basura? Si quieres realizar comprobación de errores en serio, utiliza `strtol`. Y por otro lado, si vamos a fallar, fallamos, no usamos un valor por defecto.
```suggestion
            int* endptr = NULL;
            opts.method = strtol(optarg, &endptr, 10);
            if (*endptr != \0) {
                fprintf(stderr, "Método de reserva inválido: '%s'.\n", optarg);
                return -1;
            }

            if (opts.method < 0 || opts.method > 2) {
                fprintf(stderr, "Método de reserva inválido.\n");
                return -1;
            }
```
https://linux.die.net/man/3/strtol

2024-04-16 09:44 UTC, Molter73 commented on src/movie.c
>          return NULL;
Nunca hagas esto, el hecho que puedas tener bloques if de una sola línea sin corchetes es una aberración, ha habido brechas de seguridad por este tipo de cosas. El cambio está agravado porque en realidad no realizaste ningún cambio real en el código, esto lo único que hace es aumentar las posibilidades que tengas un conflicto con algún compañero.
```suggestion
    if (seats == NULL) {
        return NULL;
    }
```

2024-04-16 09:44 UTC, Molter73 commented on .vscode/settings.json
Veo que no has quitado este archivo, si no lo quieres eliminar en tu ordenador, muévelo a otro directorio, en ese punto git debería permitirte marcarlo como eliminado, realiza el commit y luego vuelve a poner el archivo en su lugar tras agregar la línea `.vscode/` al `.gitignore` como te indiqué en el review anterior.

2024-04-16 09:44 UTC, Molter73 commented on src/movie.c
> +    if (col >= m->ncols || row >= m->nrows)
Y por qué quitas el assert? Vuelve a agregarlo y ponle corchetes al if
```suggestion
    assert(m != NULL);

    if (col >= m->ncols || row >= m->nrows) {
```

2024-04-16 09:44 UTC, Molter73 commented on src/movie.c
>          return false;
```suggestion
    if (seat->reserved) {
        return false;
    }
```

2024-04-16 09:44 UTC, Molter73 commented on src/client.c
> +    case 0:
El enum propuesto en un comentario anterior también iría bien aquí
```suggestion
void client_destroy_mutexes(locking_method method, int nrows, int ncols) {
    switch (method) {
    case GLOBAL:
```

2024-04-16 13:50 UTC, Molter73 commented on .github/workflows/main.yml
> -          ./movies \
Esta no es la línea donde pedí el cambio, es en el bloque de `ThreadSanitizer`

2024-04-16 13:50 UTC, Molter73 commented on src/client.c
> +    client_res_t* res = client_res_new();
Esto no hace falta que se reserve en la sección crítica, cada hebra reserva la suya propia y por lo tanto no puede tener condiciones de carrera.

2024-04-16 13:50 UTC, Molter73 commented on src/client.c
> +    client_res_t* res = client_res_new();
También hace falta chequear si `res` es NULL y fallar en esta condición.
```suggestion
    client_res_t* res = client_res_new();
    if (res == NULL) {
        return NULL;
    }
```

2024-04-16 13:50 UTC, Molter73 commented on src/client.c
> +    client_res_t* res = client_res_new();
Estos últimos dos comentarios aplican en las tres implementaciones de client_run

2024-04-16 13:50 UTC, Molter73 commented on src/client.c
> +    int row = id % movie->nrows;
La fila se debe elegir de forma aleatoria, si no limitas la cantidad de condiciones de carrera a sólo las hebras con la misma fila, y no es lo que queremos.
```suggestion
    int row = rand_r(&seed) % movie->nrows;
```

2024-04-16 13:50 UTC, Molter73 commented on src/client.c
> +    }
Esto qué hace aquí? Haciendo esto estás creando una hebra y esperando que termine antes que se cree la siguiente, revierte todo este cambio.
La comprobación del resultado y liberación de res se debe realizar en esta línea de main.c, donde esperamos tras haber creado TODAS las hebras:
https://github.com/Molter73/movies/blob/842bff9627a050dbb174ef9f5766170cd8cd8879/src/main.c#L64

2024-04-16 13:50 UTC, Molter73 commented on src/client.c
> +        free(client);
Por qué se cambió la indentación de esta línea?

2024-04-16 14:23 UTC, bmsjale93 commented on src/client.c
> +        free(client);
Fallo de teclado, al trabajar en Ubuntu no se donde está cada cosa :(

2024-04-16 14:27 UTC, bmsjale93 commented on src/client.c
> +    }
He vuelto a modificar este cambio para volver atrás pero el Sanitizer me sigue generando problemas, que debería hacer para que pase los checks?

2024-04-16 15:44 UTC, Molter73 commented on src/client.c
> +    }
Tienes que haces lo mismo que hacías aquí, pero después del `pthread_join` que está en main.c, la diferencia es que hay que tomar `res` del llamado a esa función, algo así:
```c
    for (int i = 0; i < opts->threads; i++) {
        client_res_t* res;
        pthread_join(clients[i]->thread, &res);

        if (res == NULL) {
            continue;
        }

        if (res->success) {
            printf("Reserva exitosa.\n");
        } else {
            printf("Reserva fallida.\n");
        }
        client_res_free(res);
    }
```
https://linux.die.net/man/3/pthread_join

2024-04-16 16:02 UTC, bmsjale93 commented on src/client.c
> +    }
Ah vale vale perfecto, le pego un cambio ahora

2024-04-17 09:21 UTC, Molter73 commented on src/main.c
> +    return -1;
Todo esto se puede simplificar muchísimo, reescribelo así:
```c
    for (int i = 0; i < opts->threads; i++) {
        client_res_t* res = NULL;
        if (pthread_join(clients[i]->thread, (void**)&res) != 0) {
            fprintf(stderr, "Fallo al esperar el hilo del cliente %d\n", i);
            continue;
        }

        if (res == NULL) {
            fprintf(stderr, "Fallo al recibir resultado de cliente %d\n", i);
            continue;
        }

        printf("Cliente %d: %s\n", res->success ? "Reserva exitosa", "Reserva fallida");
        client_res_free(res);
    }

    res = 0;

cleanup:
    for (int i = 0; i < opts->threads && clients[i] != NULL; i++) {
        client_free(clients[i]);
    }
    free(clients);
    client_destroy_mutexes(opts->method, opts->rows, opts->cols);
    movie_free(movie);
    return res;
```

2024-04-17 13:03 UTC, Molter73 commented on src/main.c
> +    return 0;
Aquí falta volver a `return res;`, si no los casos de error también devolverán que la ejecución fue correcta.

2024-04-17 13:03 UTC, Molter73 commented on src/main.c
> +        return -1;
Esto se me pasó en la revisión anterior, vuelve a poner `goto cleanup;` aquí y vuelve a agregar la variable `res`.

2024-04-17 16:15 UTC, Molter73 commented on src/main.c
> +    int res = 0;
res tiene que inicializarse a -1 y se debe poner a 0 antes de la etiqueta `cleanup`, de esta forma los `goto cleanup` siempre generan un error y llegar al final de la función correctamente hace que termine con 0. Mira cómo está en los cambios del PR o directamente en la rama principal.

2024-04-17 18:34 UTC, Molter73 approved these changes

2024-04-17 18:34 UTC, merged